# Header
menu:
  Home: /
rss: /atom.xml
title: Bruno Luiz da Silva

# Content
excerpt_link: Read More

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
